### ISSUE TITLE
Get taxonomy terms meta data

### ISSUE THREAD

**Issue by everlast000** [gizburdt/wp-cuztom#338]
Hi! I'm heaving trouble getting meta data from my taxonomies.

I have this:

```
$taxonomy->add_term_meta (
        array(
            array(
                'name'        => 'type_id',
                'label'       => 'ID',
                'type'        => 'text'
            )
        )
);
```

And to get the terms, I use:

```
$schipargs = array(
			'hide_empty' => false, 
			'fields' => 'all',
		 );
		 
		$terms = get_terms( 'schiptype', $schipargs );
		
		if ( ! empty( $terms ) && ! is_wp_error( $terms ) ){
			
			echo '<ul>';
			foreach ( $terms as $term ) {
				
				$type_id = get_cuztom_term_meta($term->term_id, $term->taxonomy);
				
				echo '<li>' . $type_id['_type_id'] . ': ' . $term->name . '</li>';
				
			}
			
			echo '</ul>';
		 
		}
```

I can get all the term names, but I just can't get the term meta data to show.

Any thoughts?

**Comment by gizburdt** [comment]
I tested your code, and it works fine with me. Can you dump `$type_id`, what do you get?

**Comment by everlast000** [comment]
Aaaah I found the problem. 

This line 
```$type_id = get_cuztom_term_meta($term->term_id, $term->taxonomy);```
wasn't working for me, I had to put "schiptype" instead of $term->taxonomy. Don't know why, but hey!! Is that not 50% of coding =p

**Comment by gizburdt** [comment]
:)
