### ISSUE TITLE
Metabox position

### ISSUE THREAD

**Issue by thesquaremedia** [gizburdt/wp-cuztom#340]
Is there a way to choose the position of the metabox.

**Comment by gizburdt** [comment]
Just like, the normal add-meta_box (https://codex.wordpress.org/Function_Reference/add_meta_box), you can pass `$context` and `$priority` to the Cuztom_Meta_Box class.

**Comment by gizburdt** [comment]
Did it work?

**Comment by thesquaremedia** [comment]
yes it did thanks
